services:
  backend: &backend
    container_name: django-api
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8008:8008"
    command: "tail -f /dev/null" # Infinite loop to keep container live doing

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start
