# Generated by Django 5.0.6 on 2024-05-28 03:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_order_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_date",
        ),
    ]
